### ISSUE TITLE
Submissions remaining query incorrect

### ISSUE THREAD

**Issue by scarroll32** [crowdAI/crowdai#746]
```

  1) SubmissionsRemainingQuery per round round:two submissions made inside window should eq [3, nil]
     Failure/Error: it { expect(subject.call).to eq([3, nil]) }

       expected: [3, nil]
            got: [5, nil]

       (compared using ==)
     # ./spec/queries/submissions_remaining_query_spec.rb:171:in `block (4 levels) in <top (required)>'
     # ./spec/rails_helper.rb:63:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:62:in `block (2 levels) in <top (required)>'

  2) SubmissionsRemainingQuery per round round:two submissions made, one outside window should eq [4, nil]
     Failure/Error: it { expect(subject.call).to eq([4, nil]) }

       expected: [4, nil]
            got: [5, nil]

       (compared using ==)
     # ./spec/queries/submissions_remaining_query_spec.rb:188:in `block (4 levels) in <top (required)>'
     # ./spec/rails_helper.rb:63:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:62:in `block (2 levels) in <top (required)>'

  3) SubmissionsRemainingQuery per round all submissions made should eq [0, nil]
     Failure/Error: it { expect(subject.call).to eq([0, nil]) }

       expected: [0, nil]
            got: [5, nil]

       (compared using ==)
     # ./spec/queries/submissions_remaining_query_spec.rb:201:in `block (4 levels) in <top (required)>'
     # ./spec/rails_helper.rb:63:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:62:in `block (2 levels) in <top (required)>'
```

**Comment by scarroll32** [comment]
Bugs in tests fixed.
