### ISSUE TITLE
`rake db:seed` fails with `relation "organizers" does not exist`

### ISSUE THREAD

**Issue by heroxbd** [crowdAI/crowdai#954]
Hi,

I am trying to set up crowdAI by following

  https://github.com/crowdAI/crowdai/blob/master/doc/technical/getting_started.md

The step of `rake db:seed` fails with `relation "organizers" does not exist`. It seems that the `seeds.rb` and the rest of the database handling modules grew out of sync.  Any hints?

The full error output is attached below:

```
rake db:seed -v -t
** Invoke db:seed (first_time)
** Execute db:seed
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Execute db:abort_if_pending_migrations
rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "organizers" does not exist
LINE 8:                WHERE a.attrelid = '"organizers"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
                     c.collname, col_description(a.attrelid, a.attnum) AS comment
                FROM pg_attribute a
                LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                LEFT JOIN pg_type t ON a.atttypid = t.oid
                LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
               WHERE a.attrelid = '"organizers"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:63:in `async_exec'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:63:in `block (2 levels) in query'
HOME/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
HOME/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
HOME/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:62:in `block in query'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block (2 levels) in log'
HOME/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:578:in `block in log'
HOME/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:569:in `log'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:61:in `query'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:749:in `column_definitions'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:113:in `columns'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/connection_adapters/schema_cache.rb:69:in `columns'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/connection_adapters/schema_cache.rb:75:in `columns_hash'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/model_schema.rb:466:in `load_schema!'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/attributes.rb:234:in `load_schema!'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/attribute_decorators.rb:51:in `load_schema!'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/model_schema.rb:459:in `block in load_schema'
HOME/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/model_schema.rb:456:in `load_schema'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/model_schema.rb:346:in `attribute_types'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/attribute_methods.rb:230:in `has_attribute?'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/inheritance.rb:55:in `new'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/persistence.rb:52:in `create!'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/persistence.rb:50:in `block in create!'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/persistence.rb:50:in `collect'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/persistence.rb:50:in `create!'
/srv/crowdai/db/seeds.rb:4:in `<top (required)>'
HOME/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `load'
HOME/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `block in load'
HOME/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
HOME/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `load'
HOME/.rvm/gems/ruby-2.5.1/gems/railties-5.2.0/lib/rails/engine.rb:551:in `load_seed'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:281:in `load_seed'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/railties/databases.rake:194:in `block (2 levels) in <top (required)>'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
HOME/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
HOME/.rvm/gems/ruby-2.5.1/bin/rake:23:in `load'
HOME/.rvm/gems/ruby-2.5.1/bin/rake:23:in `<main>'
HOME/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
HOME/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'

Caused by:
PG::UndefinedTable: ERROR:  relation "organizers" does not exist
LINE 8:                WHERE a.attrelid = '"organizers"'::regclass
                                          ^
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:63:in `async_exec'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:63:in `block (2 levels) in query'
HOME/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
HOME/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
HOME/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:62:in `block in query'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block (2 levels) in log'
HOME/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:578:in `block in log'
HOME/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:569:in `log'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:61:in `query'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:749:in `column_definitions'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:113:in `columns'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/connection_adapters/schema_cache.rb:69:in `columns'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/connection_adapters/schema_cache.rb:75:in `columns_hash'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/model_schema.rb:466:in `load_schema!'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/attributes.rb:234:in `load_schema!'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/attribute_decorators.rb:51:in `load_schema!'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/model_schema.rb:459:in `block in load_schema'
HOME/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/model_schema.rb:456:in `load_schema'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/model_schema.rb:346:in `attribute_types'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/attribute_methods.rb:230:in `has_attribute?'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/inheritance.rb:55:in `new'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/persistence.rb:52:in `create!'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/persistence.rb:50:in `block in create!'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/persistence.rb:50:in `collect'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/persistence.rb:50:in `create!'
/srv/crowdai/db/seeds.rb:4:in `<top (required)>'
HOME/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `load'
HOME/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `block in load'
HOME/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
HOME/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `load'
HOME/.rvm/gems/ruby-2.5.1/gems/railties-5.2.0/lib/rails/engine.rb:551:in `load_seed'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/tasks/database_tasks.rb:281:in `load_seed'
HOME/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.0/lib/active_record/railties/databases.rake:194:in `block (2 levels) in <top (required)>'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
HOME/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
HOME/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
HOME/.rvm/gems/ruby-2.5.1/bin/rake:23:in `load'
HOME/.rvm/gems/ruby-2.5.1/bin/rake:23:in `<main>'
HOME/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
HOME/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => db:seed
  Organizer Load (2.1ms)SELECT "organizers".* FROM "organizers"
  (0.7ms) SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
```

**Comment by scarroll32** [comment]
Hi @heroxbd thanks for logging this issue. It does sound like the schema.rb file is missing or empty.

I just ran ```rails db:reset``` and it has loaded the schema and all seeds OK. Could you try that?

Incidentally, we are currently working on a Docker Compose version of a full development environment. There are a few issues around webpacker to be worked though, but the branch is [here](https://github.com/crowdAI/crowdai/pull/951) if you are interested. Contributions welcome!

**Comment by heroxbd** [comment]
Thank you, Sean for your prompt reply!

> Hi @heroxbd thanks for logging this issue. It does sound like the schema.rb file is missing or empty.

schema.rb is not empty.  It is from the repository vanilla.

> I just ran rails db:reset and it has loaded the schema and all seeds OK. Could you try that?

Interesting!  `rake db:reset` works.  But the command sequence of `rake db:create`, `rake db:migrate` and `rake:seed` does not.

> Incidentally, we are currently working on a Docker Compose version of a full development environment. There are a few issues around webpacker to be worked though, but the branch is here if you are interested. Contributions welcome!

Thanks.  We will give it a try.

**Comment by heroxbd** [comment]
FYI, the `rake db:reset` is not equivalent to consecutive invocation of `rake db:create`, `rake db:migrate` and `rake:seed`.

```
% rake db:reset -v -t -n
** Invoke db:reset (first_time)
** Invoke db:drop (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute (dry run) environment
** Execute (dry run) db:load_config
** Invoke db:check_protected_environments (first_time)
** Invoke db:load_config
** Execute (dry run) db:check_protected_environments
** Execute (dry run) db:drop
** Invoke db:setup (first_time)
** Invoke db:schema:load_if_ruby (first_time)
** Invoke db:create (first_time)
** Invoke db:load_config
** Execute (dry run) db:create
** Invoke environment
** Execute (dry run) db:schema:load_if_ruby
** Invoke db:structure:load_if_sql (first_time)
** Invoke db:create
** Invoke environment
** Execute (dry run) db:structure:load_if_sql
** Invoke db:seed (first_time)
** Execute (dry run) db:seed
** Execute (dry run) db:setup
** Execute (dry run) db:reset

```

**Comment by scarroll32** [comment]
Priming migration created and documentation updated. https://github.com/crowdAI/crowdai/commit/be067a9239f21d36c962201f96f18bd4737424e1

Thanks @heroxbd

**Comment by heroxbd** [comment]
Thanks, Sean!
