### ISSUE TITLE
force using webpack 3

### ISSUE THREAD

**Issue by heroxbd** [crowdAI/crowdai#960]
Hi,

I am trying to set up crowdAI, following

  https://github.com/crowdAI/crowdai/blob/master/doc/technical/getting_started.md

together with the `rake db:reset` hack mentioned in #954.  After downloading the node.js parts by yarn, I met errors attached below in the appendix.  Upon closer investigation, the webpack installed in node_modules is Version 4. But from yarn.lock in the git repository, webpack 3 has been used by the developers.

The discussion on [webpack upstream](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/701) suggests that webpack 4 breaks the Chunk module.

So, is there a way to force crowdAI to use webpack 3?

Cheers,
Benda

Appendix of error messages.

```
$ foreman start -f Procfile.dev
18:28:25 web.1       | started with pid 36064
18:28:25 webpacker.1 | started with pid 36065
18:28:25 worker.1    | started with pid 36066
18:28:26 webpacker.1 | yarn run v1.9.4
18:28:26 webpacker.1 | warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
18:28:26 webpacker.1 | $ /srv/crowdai/node_modules/.bin/webpack-dev-server --progress --color --config /srv/crowdai/config/webpack/development.js
18:28:28 webpacker.1 |  10% building modules 1/1 modules 0 active(node:36084) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
18:28:28 webpacker.1 | ℹ ｢wds｣: Project is running at http://0.0.0.0:8080/
18:28:28 webpacker.1 | ℹ ｢wds｣: webpack output is served from http://0.0.0.0:8080/packs/
18:28:28 webpacker.1 | ℹ ｢wds｣: Content not from webpack is served from /srv/crowdai/public/packs
18:28:28 webpacker.1 | ℹ ｢wds｣: 404s will fallback to /index.html
^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H ^H 77% module and chunk tree optimization unnamed compat plugin/srv/crowdai/node_modules/webpack/lib/Chunk.js:824
18:28:35 webpacker.1 |          throw new Error(
18:28:35 worker.1    | 2018-08-27T09:28:33.955Z 36066 TID-gop33n8em INFO: Booting Sidekiq 5.1.3 with redis options {:id=>"Sidekiq-server-PID-36066", :url=>nil}
18:28:35 webpacker.1 |          ^
18:28:35 worker.1    |   Organizer Load (0.7ms)  SELECT "organizers".* FROM "organizers"
18:28:35 webpacker.1 |
18:28:35 worker.1    |   Organizer Load (0.5ms)  SELECT "organizers".* FROM "organizers"
18:28:35 webpacker.1 | Error: Chunk.entrypoints: Use Chunks.groupsIterable and filter by instanceof Entrypoint instead
18:28:35 webpacker.1 |     at Chunk.get (/srv/crowdai/node_modules/webpack/lib/Chunk.js:824:9)
18:28:35 webpacker.1 |     at /srv/crowdai/node_modules/extract-text-webpack-plugin/dist/index.js:176:48
18:28:35 webpacker.1 |     at Array.forEach (<anonymous>)
18:28:35 webpacker.1 |     at /srv/crowdai/node_modules/extract-text-webpack-plugin/dist/index.js:171:18
18:28:35 webpacker.1 |     at AsyncSeriesHook.eval [as callAsync] (eval at create (/srv/crowdai/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:14:1)
18:28:35 webpacker.1 |     at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/srv/crowdai/node_modules/tapable/lib/Hook.js:35:21)
18:28:35 webpacker.1 |     at Compilation.seal (/srv/crowdai/node_modules/webpack/lib/Compilation.js:1213:27)
18:28:35 webpacker.1 |     at hooks.make.callAsync.err (/srv/crowdai/node_modules/webpack/lib/Compiler.js:547:17)
18:28:35 webpacker.1 |     at _err0 (eval at create (/srv/crowdai/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
18:28:35 webpacker.1 |     at _addModuleChain (/srv/crowdai/node_modules/webpack/lib/Compilation.js:1064:12)
18:28:35 webpacker.1 |     at processModuleDependencies.err (/srv/crowdai/node_modules/webpack/lib/Compilation.js:980:9)
18:28:35 webpacker.1 |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
18:28:35 webpacker.1 |     at process._tickCallback (internal/process/next_tick.js:180:9)
18:28:35 webpacker.1 | error Command failed with exit code 1.

```

**Comment by heroxbd** [comment]
It turns out that an invocation of `yarn install` is needed.  Preparing for a pull request to improve documentation.

**Comment by scarroll32** [comment]
Docs updated https://github.com/crowdAI/crowdai/commit/93085bb1669f0b24d7b1655797c06f50c4bde774

**Comment by heroxbd** [comment]
Thanks, Sean!
